// The purpose of this function is to generate a random number between 1 and 3.

function randomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min);
}

// The purpose of this function is to "link" number generated by previous function to 
// one of three possible computer choices.

function computerPlay(computerChoice) {

    randomValue = randomInt(1, 3);

    if (randomValue === 1) {
        return computerChoice = "rock";
    } else if (randomValue === 2) {
        return computerChoice = "paper";
    } else if (randomValue === 3) {
        return computerChoice = "scissors";
    } 
}

let playerPoints = 0;
let computerPoints = 0;

const resultDisplay = document.querySelector("div");
const player = document.querySelector("#player");
const computer = document.querySelector("#computer");
const winner = document.querySelector("#winner");


// A single round of the game. Depending on the result, one of the messages is displayed and either 
// the player or the computer gets a point (unles it's a tie). 

function singleRound(playerSelection, computerSelection) {

    computerSelection = computerPlay();

    if (playerPoints === 5 || computerPoints === 5) {
        if (playerPoints === 5) {
            return winner.textContent = "Human has won!";
        } else {
            return winner.textContent = "Computer has won!";
        }
    }

    if (playerSelection === computerSelection) {
        return resultDisplay.textContent = "It is a tie!";
    } else if ((playerSelection === "rock") && (computerSelection === "paper")) {
        computerPoints += 1;
        computer.textContent = "Computer points: " + computerPoints;
        return resultDisplay.textContent = "You chose rock and computer chose paper, so you lost!";
    } else if ((playerSelection === "rock") && (computerSelection === "scissors")) {
        playerPoints += 1;
        player.textContent = "Player points: " + playerPoints;
        return resultDisplay.textContent = "Congratulations! You chose rock and computer chose scissors, so you won!";        
    } else if ((playerSelection === "paper") && (computerSelection === "rock")) {
        playerPoints += 1;
        player.textContent = "Player points: " + playerPoints;
        return resultDisplay.textContent = "Congratulations! You chose paper and computer chose rock, so you won!";
    } else if ((playerSelection === "paper") && (computerSelection === "scissors")) {
        computerPoints += 1;
        computer.textContent = "Computer points: " + computerPoints;
        return resultDisplay.textContent = "You chose paper and computer chose scissors, so you lost!";  
    } else if ((playerSelection === "scissors") && (computerSelection === "rock")) {
        computerPoints += 1;
        computer.textContent = "Computer points: " + computerPoints;
        return resultDisplay.textContent = "You chose scissors and computer chose rock, so you lost!"; 
    } else {
        playerPoints += 1;
        player.textContent = "Player points: " + playerPoints;
        return resultDisplay.textContent = "Congratulations! You chose scissors and computer chose paper, so you won!";
    }
    
}

// Playing singleRound() with all three possible player's choices in order to make adding event 
// listener to buttons more straightforward.

function rocking() {
    singleRound("rock");
}

function scissoring() {
    singleRound("scissors");
}

function papering() {
    singleRound("paper");
}

// Linking possible player's choices to the buttons and playing rounds when buttons are clicked.

const playerRock = document.querySelector('#rock');
playerRock.addEventListener("click", rocking);

const playerPaper = document.querySelector("#paper");
playerPaper.addEventListener("click", papering);

const playerScissors = document.querySelector("#scissors");
playerScissors.addEventListener("click", scissoring);




// The actual game. Single round is played five times, points are calculated and the final message
// is displayed telling the user who won.

//function game(results) {
    //singleRound();
    //singleRound();
    //singleRound();
    //singleRound();
    //singleRound();

    //if (playerPoints === computerPoints) {
        //return results = console.log("It is a tie! You won: " + playerPoints + ". Computer won: " + computerPoints);
    //} else if (playerPoints > computerPoints) {
        //return results = console.log("Congratulations! You won: " + playerPoints + ". Computer won: " + computerPoints);
    //} else {
        //return results = console.log("Unfortunately, you won: " + playerPoints + ". Computer won: " + computerPoints);
    //}
//}

